// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-NqOhNVIyEFFT8pgYz-L3SVwhXNsIaBc',
    appId: '1:763085252761:web:e95fc916501886dbd7b008',
    messagingSenderId: '763085252761',
    projectId: 'project-2-ad91d',
    authDomain: 'project-2-ad91d.firebaseapp.com',
    storageBucket: 'project-2-ad91d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJdfoyi7CpnsZk1t278IthzdCo9dhmpvE',
    appId: '1:763085252761:android:84d6af4a6289bb17d7b008',
    messagingSenderId: '763085252761',
    projectId: 'project-2-ad91d',
    storageBucket: 'project-2-ad91d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJO1RGtT5jZpX6xoazXkS9EV7oWwY8KxA',
    appId: '1:763085252761:ios:43108d3e14f302abd7b008',
    messagingSenderId: '763085252761',
    projectId: 'project-2-ad91d',
    storageBucket: 'project-2-ad91d.appspot.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJO1RGtT5jZpX6xoazXkS9EV7oWwY8KxA',
    appId: '1:763085252761:ios:43108d3e14f302abd7b008',
    messagingSenderId: '763085252761',
    projectId: 'project-2-ad91d',
    storageBucket: 'project-2-ad91d.appspot.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-NqOhNVIyEFFT8pgYz-L3SVwhXNsIaBc',
    appId: '1:763085252761:web:4af5e1ee98eba71bd7b008',
    messagingSenderId: '763085252761',
    projectId: 'project-2-ad91d',
    authDomain: 'project-2-ad91d.firebaseapp.com',
    storageBucket: 'project-2-ad91d.appspot.com',
  );
}
